# LLM Configuration
llm:
  # Provider options: 'ollama', 'openai', or 'gemini'
  provider: gemini
  
  # Ollama settings (when provider=ollama)
  ollama:
    base_url: http://localhost:11434
    model: qwen:7b-chat  
  
  # OpenAI settings (when provider=openai)
  openai:
    api_key: 
    model: gpt-4o 
    
  # Gemini settings (when provider=gemini)
  gemini:
    api_key: 
    model: gemini-2.5-flash  # Using 2.5-flash with thinking disabled
  
  # Model-specific settings for different tasks
  models:
    # For pattern identification (Script 01 - get_llm_patterns)
    pattern_identification:
      temperature: 0.0
      max_tokens: 8192  
      
    # For candidate phrase generation (Script 01 - get_candidate_phrases)
    candidate_generation:
      temperature: 0.0
      max_tokens: 9000 
      
    # For counterfactual generation (Script 02)
    counterfactual_generation:
      temperature: 0.0
      max_tokens: 8000  
      stop: ["\n"]
      
    # For semantic filtering (Script 03)
    semantic_filtering:
      temperature: 0.0
      max_tokens: 8000
      
    # For discriminator filtering (Script 03)
    discriminator_filtering:
      temperature: 0.0
      max_tokens: 8000

# Dataset Configuration
dataset:
  # Training dataset
  train_file: emotions_train.csv  # filename in input_data/ folder
  
  # Test dataset (for evaluation in Script 05)
  test_file: emotions_test.csv   # filename in input_data/ folder
  
  # Column names in CSV
  columns:
    id: id
    text: example
    label: Label
  
  # Label to exclude from counterfactual generation (e.g., 'none', 'neutral', null values)
  exclude_labels:
    - none
    - None
    - null
    - ""

# Processing Settings
processing:
  # Random seed for reproducibility
  seed: 42
  
  # Enhanced: Maximum examples per label for pattern identification (removed global limit)
  max_examples_per_label: 50  # Increased from 10 to 50 per label
  
  # Token budget limit (increased for larger datasets)
  token_limit: 20000000  # Increased from 10M to 20M (~$100 budget vs original $3)
  
  # Maximum counterfactuals per original example (Script 05)
  max_counterfactuals_per_example: 6  # Increased from 4 to 6
  
  # Enhanced: Expanded sample sizes for evaluation (up to 300-shot)
  evaluation_shots: [10, 15, 30, 50, 70, 90, 120]
  
  # Enhanced: Multiple seeds for robust evaluation (10 seeds for statistical significance)
  evaluation_seeds: [42]

# Directory Configuration
directories:
  input_data: input_data
  output_data: output_data
  interim_output: output_data/interim_output
  archive: output_data/archive
